### ISSUE TITLE
Feature Request: An electron App?

### ISSUE THREAD

**Issue by xypnox** [zuck/alighieri#1]
It is a nice editor but would shine if it was an electron app.

**Comment by zuck** [comment]
Yes, I will port the whole codebase to latest version of Quasar Framework and then add an official electron app.

Actually it's already there, but you have to build it by yourself typing:

`quasar build && npm run package-electron [linux|darwin|win]`

**Comment by zuck** [comment]
Starting from 0.8.x releases you can simply build it with:

```
npm install && quasar build -m electron
```

**Comment by zuck** [comment]
Add a GitHub Actions workflow to release a packaged version of the Electron app on each new tag:

https://github.com/zuck/alighieri/releases/tag/v0.9.4
