### ISSUE TITLE
images?

### ISSUE THREAD

**Issue by grupie001** [zuck/alighieri#2]
It would be perfect to implement images. Maybe via link (e.g. cloudinary)
What do you mean.
Cheers & nice work

**Comment by zuck** [comment]
Hi @grupie001,

while in general I agree that adding image support will help some use-cases, I'm not sure if they are a good addition for the main target of this app: writers and novelists. Still thinking about it...

**Comment by zuck** [comment]
Fix with 5efee6489184e2e95f91324e7f4dcfa115b8320e.
