### ISSUE TITLE
quasar' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by arunonsite** [zuck/alighieri#3]
'quasar' is not recognized as an internal or external command for windows 10 cmd.

Can you please advice.

**Comment by zuck** [comment]
Hi @arunonsite.

I think the problem here is **quasar-cli** is not installed globally.

Could you please try with the following and give feedback if it does fix the issue, please?

```bash
$ npm install -g quasar-cli
```

More info at:

https://forum.quasar-framework.org/topic/412/windows-10-won-t-read-quasar-cli/5
